### ISSUE TITLE
when launched in vmware it crashes

### ISSUE THREAD

**Issue by phra** [roccomuso/kickthemout#3]
hi.

when launching the application inside an vmware virtual machine in bridge mode (so no NAT involved) the application crashes with the following message:

```
? What to do? Start KickThemOut
? Select the network Interface: ens33
  Scanning LAN.. |events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn arp ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

the guest machine is running debian testing while the host machine is running the latest windows.

**Comment by roccomuso** [comment]
@phra What OS runs on the VM?
Probably the cli `arp` tools is missing ([here](https://github.com/nekuz0r/node-arp/blob/master/lib/arp.js#L48)).
Error raised from the `node-arp` dependency.

**Comment by phra** [comment]
i'm running kali linux and, yes, the arp command is not available. i've installed net-tools but it's still missing.

**Comment by roccomuso** [comment]
ok. It seems a cli [deprecated tool](https://dougvitale.wordpress.com/2011/12/21/deprecated-linux-networking-commands-and-their-replacements/). It's worth make a PR to `node-arp` and have a fallback cmd perhaps.
