### ISSUE TITLE
TypeError when scanning LAN

### ISSUE THREAD

**Issue by wayne5540** [roccomuso/kickthemout#5]
```sh
? What to do? Start KickThemOut
? Select the network Interface: en0

/Users/wayne/.nvm/versions/node/v7.5.0/lib/node_modules/kickthemout/index.js:71
      network.iface.gateway_mac_address = (_.find(hosts, {'ip': iface.gateway_ip})).mac
                                                                                   ^

TypeError: Cannot read property 'mac' of undefined
    at /Users/wayne/.nvm/versions/node/v7.5.0/lib/node_modules/kickthemout/index.js:71:84
    at /Users/wayne/.nvm/versions/node/v7.5.0/lib/node_modules/kickthemout/lib/Network.js:55:15
    at ChildProcess.<anonymous> (/Users/wayne/.nvm/versions/node/v7.5.0/lib/node_modules/kickthemout/node_modules/node-arp/lib/arp.js:168:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

**Comment by roccomuso** [comment]
@wayne5540 could you try starting it in debug mode? `sudo DEBUG=kickthemout:* kickthemout`
Is that your default interface?
What's your OS?

**Comment by wayne5540** [comment]
OS: OSX EL Capitan 10.11.6 (15G1217)

```sh
? Select the network Interface: en0
  kickthemout:Inquiries Selected interface: { name: 'en0',
  type: 'Wireless',
  ip_address: '172.16.8.174',
  mac_address: 'my mac address',
  gateway_ip: '172.16.8.1',
  netmask: '255.255.252.0' } +5s
  kickthemout:Network Starting host discovery in LAN +2ms
  Scanning LAN.. -  kickthemout:flow hosts found: [ { ip: '172.16.8.174', mac: 'my mac address' } ] +12s
/Users/wayne/.nvm/versions/node/v7.5.0/lib/node_modules/kickthemout/index.js:71
      network.iface.gateway_mac_address = (_.find(hosts, {'ip': iface.gateway_ip})).mac
                                                                                   ^

TypeError: Cannot read property 'mac' of undefined
    at /Users/wayne/.nvm/versions/node/v7.5.0/lib/node_modules/kickthemout/index.js:71:84
    at /Users/wayne/.nvm/versions/node/v7.5.0/lib/node_modules/kickthemout/lib/Network.js:55:15
    at ChildProcess.<anonymous> (/Users/wayne/.nvm/versions/node/v7.5.0/lib/node_modules/kickthemout/node_modules/node-arp/lib/arp.js:168:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

**Comment by roccomuso** [comment]
could you execute and paste the result of `arp -a` on your terminal? thanks.
It seems that when scanning it doesn't find the IP of the Gateway.

**Comment by AlexRusbridge** [comment]
Hi, I'm getting the same problem too.

OS: MacOS Sierra 10.12.4 (16E195)
Device: MacBookPro12,1

Heres my `sudo DEBUG=kickthemout:* kickthemout` output:
```
? Select the network Interface: en0
  kickthemout:Inquiries Selected interface: { name: 'en0',
  type: 'Wireless',
  ip_address: '192.168.0.23',
  mac_address: 'ac:bc:32:77:aa:c1',
  gateway_ip: '192.168.0.1',
  netmask: '255.255.255.0' } +4s
  kickthemout:Network Starting host discovery in LAN +2ms
  Scanning LAN.. |  kickthemout:flow hosts found: [ { ip: '192.168.0.11', mac: 'a0:18:28:f3:5b:2e' },
  { ip: '192.168.0.18', mac: '78:4f:43:4d:26:e3' },
  { ip: '192.168.0.19', mac: 'ec:71:db:e8:a8:f2' },
  { ip: '192.168.0.23', mac: 'ac:bc:32:77:aa:c1' },
  { ip: '192.168.0.255', mac: 'ff:ff:ff:ff:ff:ff' },
  { ip: '192.168.0.20', mac: '50:1a:c5:4b:fd:d4' } ] +12s
/usr/local/lib/node_modules/kickthemout/index.js:71
      network.iface.gateway_mac_address = (_.find(hosts, {'ip': iface.gateway_ip})).mac
                                                                                   ^

TypeError: Cannot read property 'mac' of undefined
    at /usr/local/lib/node_modules/kickthemout/index.js:71:84
    at /usr/local/lib/node_modules/kickthemout/lib/Network.js:55:15
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/kickthemout/node_modules/node-arp/lib/arp.js:168:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```

And heres my `arp -a` output:

```
❯ arp -a
skyrouter.home (192.168.0.1) at c0:3e:f:c6:76:24 on en0 ifscope [ethernet]
apple-tv (192.168.0.11) at a0:18:28:f3:5b:2e on en0 ifscope [ethernet]
? (192.168.0.14) at (incomplete) on en0 ifscope [ethernet]
macbook-pro (192.168.0.18) at 78:4f:43:4d:26:e3 on en0 ifscope [ethernet]
unknown (192.168.0.19) at ec:71:db:e8:a8:f2 on en0 ifscope [ethernet]
? (192.168.0.20) at 50:1a:c5:4b:fd:d4 on en0 ifscope [ethernet]
alex-macbookpro (192.168.0.23) at ac:bc:32:77:aa:c1 on en0 ifscope permanent [ethernet]
? (192.168.0.255) at ff:ff:ff:ff:ff:ff on en0 ifscope [ethernet]
? (224.0.0.251) at 1:0:5e:0:0:fb on en0 ifscope permanent [ethernet]
? (239.255.255.250) at 1:0:5e:7f:ff:fa on en0 ifscope permanent [ethernet]
broadcasthost (255.255.255.255) at ff:ff:ff:ff:ff:ff on en0 ifscope [ethernet]
```

**Comment by roccomuso** [comment]
Fixed in [v1.1.13](https://www.npmjs.com/package/kickthemout) with c1e62d5.
Update and let me know, thanks!

**Comment by AlexRusbridge** [comment]
Thanks! It works :)

**Comment by wayne5540** [comment]
Thank you @roccomuso for responding/fixing so fast. It works now. :1st_place_medal:  👍
