### ISSUE TITLE
When running inside npm

### ISSUE THREAD

**Issue by wok3n** [roccomuso/kickthemout#9]
root@root:~/npm# sudo kickthemout
module.js:538
    throw err;
    ^

Error: Cannot find module './build/Release/pcap_binding'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/kickthemout/node_modules/pcap/pcap.js:3:21)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by roccomuso** [comment]
Which version of node?
Did the `npm install -g kickthemout` installation go well?
